version: '3.9'

services:
  sirius_api:
    build: .
    container_name: sirius_api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app        # Só monta a pasta de código
      - ./requirements.txt:/app/requirements.txt
    restart: unless-stopped
